# Generated by Django 3.1.3 on 2020-11-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sellproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Enter your name', max_length=100)),
                ('product', models.CharField(default='What do you want to sell', max_length=100)),
                ('cost', models.IntegerField(max_length=100)),
            ],
        ),
    ]
