# Generated by Django 3.0.7 on 2020-11-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201107_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
