# Generated by Django 3.1.3 on 2020-11-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_sellproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='issold',
            field=models.BooleanField(default=True),
        ),
    ]
