# Generated by Django 3.1.3 on 2020-11-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_sellproduct_issold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
