# Generated by Django 3.1.3 on 2020-11-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20201107_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='phonenumber',
            field=models.TextField(default='00000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
