# Generated by Django 3.1.3 on 2020-11-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20201107_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='issold',
            field=models.BooleanField(default='False'),
        ),
    ]
