# Generated by Django 3.1.3 on 2020-11-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20201108_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
    ]
